name: Trigger for deploy

on:
  push:
    branches: [ main ]

jobs:
  notify-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger to repo deploy workflow
        run: |
          echo "🚀 Disparando deploy en repositorio del deployment ..."
          curl --request POST \
            --url https://api.github.com/repos/convidauam/convida_deployment/dispatches \
            --header 'Accept: application/vnd.github+json' \
            --header 'Authorization: Bearer ${{ secrets.GHP_TOKEN }}' \
            --header 'Content-Type: application/json' \
            --header 'X-GitHub-Api-Version: 2022-11-28' \
            --data '{
            "event_type": "deploy-trigger"
          }'
