name: Trigger deploy

on:
  push:
    branches: [ main ]

jobs:
  notify-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger to repo deploy workflow
        run: |
          echo "🚀 Disparando deploy en Repo de deployment..."
          curl -X POST \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
            https://api.github.com/repos/convidauam/convida_deployment/dispatches \
            -d '{"event_type": "deploy-trigger"}'
